apiVersion: apps/v1
kind: Deployment
metadata:
  name: vargavendel-backend-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: vargavendel-backend
  template:
    metadata:
      labels:
        app: vargavendel-backend
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: vargavendel-backend
          image: ghcr.io/vargavendel/vargavendel-backend:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/name
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/name
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: vargavendel-backend-cluster-ip-service
spec:
  selector:
    app: vargavendel-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vargavendel-backend-certificate
spec:
  secretName: vargavendel-backend-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.vargavendel.dev
